DROP DATABASE IF EXISTS MENU; 

CREATE DATABASE MENU; 

USE MENU; 

CREATE TABLE Students(
	student_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	fname VARCHAR(256) NOT NULL, 
	lname VARCHAR(256) NOT NULL,
	password VARCHAR(256) NOT NULL
); 

CREATE TABLE Favorites(
	student_id INT NOT NULL, 
	meal VARCHAR(256) NOT NULL, 
	img VARBINARY(MAX), 
	FOREIGN KEY (student_id) REFERENCES Students(student_id)
); 

